---
general:
  buildTool: "mta"

service:
  buildToolVersion: "MBTJ25N24"

stages:
  Build:
    npmExecuteLint: false

  Additional Unit Tests:
    npmExecuteScripts: false

  Malware Scan:
    malwareExecuteScan: true

  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false

  Compliance:
    sonarExecuteScan: false

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "726101a8trial"
    cfSpace: "dev"
    cfCredentialsId: "deployonbtp"
    deployType: "default"
    tmsUpload: false

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
