---
stages:
  build:
    buildTool: "mta"
    buildDescriptor: "mta.yaml"
    buildToolVersion: "MBTJ11N20"
  malwareScan:
    scan: false

  release:
    cfDeploy:
      strategy: "default"
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "726101a8trial"
      space: "dev"
      credential: "deployonbtp"
